### ISSUE TITLE
Loss of file pyramid.py?

### ISSUE THREAD

**Issue by lawgeorge202** [ywcmaike/2018--ZJUAI-Pyr-amidBoxDetector#1]
I find that the module `pyramid` is lost in your repo. Do the file `pyramid.py` the same as `https://github.com/Goingqs/PyramidBox/blob/master/pyramid.py` ? When I use the code from Goingqs to test just one picture, it goes wrong with: `RuntimeError: CUDA out of memory. ` Is there any other config that I should change? I will be appreciate if you can upload your `pyramid.py`. Thank!

**Comment by ywcmaike** [comment]
have uploaded pyramid.py.  
I run the model with Titan 12G
